#FROM rmohr/activemq:5.15.9-alpine
FROM rmohr/activemq:5.15.9-alpine
COPY --chown=activemq:activemq activemq.xml /opt/activemq/config

#FROM symptoma/activemq:5.16.3
#COPY --chown=activemq:activemq activemq.xml /conf/activemq.xml
#COPY --chown=activemq:activemq jetty.xml /conf/jetty.xml
